# Loading libraries and data

In [2]:
import pandas as pd
from datetime import datetime

In [32]:
df_test = pd.read_csv('data\BPI_Challenge_2012\BPI_Challenge_2012-test.csv')
df_train = pd.read_csv('data\BPI_Challenge_2012\BPI_Challenge_2012-training.csv')

# Convert timestamp to datetime

In [33]:
date_list = []

for time in df_train['event time:timestamp']:
    datex = time[:-4]
    date = datetime.strptime(datex, '%d-%m-%Y %H:%M:%S')

    date_list.append(date)

In [34]:
df_train['time and date'] = date_list

In [35]:
df_train

,eventID,case concept:name,case REG_DATE,case AMOUNT_REQ,event concept:name,event lifecycle:transition,event time:timestamp,time and date
0,0,173688,2011-10-01T00:38:44.546+02:00,20000,A_SUBMITTED,COMPLETE,01-10-2011 00:38:44.546,2011-10-01 00:38:44
1,1,173688,2011-10-01T00:38:44.546+02:00,20000,A_PARTLYSUBMITTED,COMPLETE,01-10-2011 00:38:44.880,2011-10-01 00:38:44
2,2,173688,2011-10-01T00:38:44.546+02:00,20000,A_PREACCEPTED,COMPLETE,01-10-2011 00:39:37.906,2011-10-01 00:39:37
3,3,173688,2011-10-01T00:38:44.546+02:00,20000,W_Completeren aanvraag,SCHEDULE,01-10-2011 00:39:38.875,2011-10-01 00:39:38
4,4294967296,173691,2011-10-01T08:08:58.256+02:00,5000,A_SUBMITTED,COMPLETE,01-10-2011 08:08:58.256,2011-10-01 08:08:58
...,...,...,...,...,...,...,...,...
214372,38835094290529,201854,2012-01-18T02:09:07.029+01:00,50000,O_CANCELLED,COMPLETE,14-03-2012 15:30:19.361,2012-03-14 15:30:19
214373,38835094290528,201854,2012-01-18T02:09:07.029+01:00,50000,A_CANCELLED,COMPLETE,14-03-2012 15:30:19.361,2012-03-14 15:30:19
214374,38835094290530,201854,2012-01-18T02:09:07.029+01:00,50000,W_Nabellen incomplete dossiers,COMPLETE,14-03-2012 15:30:23.187,2012-03-14 15:30:23
214375,35858681954366,199678,2012-01-10T19:16:52.800+01:00,30000,W_Nabellen offertes,START,14-03-2012 15:36:15.299,2012-03-14 15:36:15
214376,35858681954367,199678,2012-01-10T19:16:52.800+01:00,30000,W_Nabellen offertes,COMPLETE,14-03-2012 15:40:34.231,2012-03-14 15:40:34

# Next event and time, and predicted next event and time

In [52]:
cases = list(df_train['case concept:name'].unique())
cases.append(list(df_test['case concept:name'].unique()))
len(cases)

10470

In [37]:
df_result = pd.DataFrame()

In [38]:
int_dict = {}
for case in cases:
    df_case = df_train[df_train['case concept:name'] == case].reset_index()
    for index, row in df_case.iterrows():
        if row['event concept:name'] in int_dict:
            if index in int_dict[row['event concept:name']]:
                int_dict[row['event concept:name']][index] += 1
            else:
                int_dict[row['event concept:name']].update({index: 1})
        else:
            int_dict[row['event concept:name']] = {index: 1}

In [39]:
#2140
position_dict = {}

for i in range(2140):
    init = 0
    task = 0
    for key in int_dict.keys():
        try:
            new = int_dict[key][i]
        except:
            new = 0
        if new > init:
            init = new
            task = key

    position_dict.update({i: task})

In [40]:
position_dict

{0: 'A_SUBMITTED',
 1: 'A_PARTLYSUBMITTED',
 2: 'W_Afhandelen leads',
 3: 'W_Afhandelen leads',
 4: 'W_Completeren aanvraag',
 5: 'W_Completeren aanvraag',
 6: 'W_Completeren aanvraag',
 7: 'W_Completeren aanvraag',
 8: 'W_Completeren aanvraag',
 9: 'W_Completeren aanvraag',
 10: 'W_Completeren aanvraag',
 11: 'W_Completeren aanvraag',
 12: 'W_Nabellen offertes',
 13: 'W_Completeren aanvraag',
 14: 'W_Nabellen offertes',
 15: 'W_Nabellen offertes',
 16: 'W_Nabellen offertes',
 17: 'W_Nabellen offertes',
 18: 'W_Nabellen offertes',
 19: 'W_Nabellen offertes',
 20: 'W_Nabellen offertes',
 21: 'W_Nabellen offertes',
 22: 'W_Nabellen offertes',
 23: 'W_Nabellen offertes',
 24: 'W_Nabellen offertes',
 25: 'W_Nabellen offertes',
 26: 'W_Nabellen offertes',
 27: 'W_Nabellen offertes',
 28: 'W_Nabellen offertes',
 29: 'W_Nabellen offertes',
 30: 'W_Nabellen offertes',
 31: 'W_Nabellen offertes',
 32: 'W_Nabellen offertes',
 33: 'W_Nabellen offertes',
 34: 'W_Nabellen offertes',
 35: 'W_Nabellen offertes',
 36: 'W_Nabellen offertes',
 37: 'W_Nabellen offertes',
 38: 'W_Nabellen incomplete dossiers',
 39: 'W_Nabellen incomplete dossiers',
 40: 'W_Nabellen incomplete dossiers',
 41: 'W_Nabellen incomplete dossiers',
 42: 'W_Nabellen incomplete dossiers',
 43: 'W_Nabellen incomplete dossiers',
 44: 'W_Nabellen incomplete dossiers',
 45: 'W_Nabellen incomplete dossiers',
 46: 'W_Nabellen incomplete dossiers',
 47: 'W_Nabellen incomplete dossiers',
 48: 'W_Nabellen incomplete dossiers',
 49: 'W_Nabellen incomplete dossiers',
 50: 'W_Nabellen incomplete dossiers',
 51: 'W_Nabellen incomplete dossiers',
 52: 'W_Nabellen incomplete dossiers',
 53: 'W_Nabellen incomplete dossiers',
 54: 'W_Nabellen incomplete dossiers',
 55: 'W_Nabellen incomplete dossiers',
 56: 'W_Nabellen incomplete dossiers',
 57: 'W_Nabellen incomplete dossiers',
 58: 'W_Nabellen incomplete dossiers',
 59: 'W_Nabellen incomplete dossiers',
 60: 'W_Nabellen incomplete dossiers',
 61: 'W_Nabellen incomplete dossiers',
 62: 'W_Nabellen incomplete dossiers',
 63: 'W_Nabellen incomplete dossiers',
 64: 'W_Nabellen incomplete dossiers',
 65: 'W_Nabellen incomplete dossiers',
 66: 'W_Nabellen incomplete dossiers',
 67: 'W_Nabellen incomplete dossiers',
 68: 'W_Nabellen incomplete dossiers',
 69: 'W_Nabellen incomplete dossiers',
 70: 'W_Nabellen incomplete dossiers',
 71: 'W_Nabellen incomplete dossiers',
 72: 'W_Nabellen incomplete dossiers',
 73: 'W_Nabellen incomplete dossiers',
 74: 'W_Nabellen incomplete dossiers',
 75: 'W_Nabellen incomplete dossiers',
 76: 'W_Nabellen incomplete dossiers',
 77: 'W_Nabellen incomplete dossiers',
 78: 'W_Nabellen incomplete dossiers',
 79: 'W_Nabellen incomplete dossiers',
 80: 'W_Nabellen incomplete dossiers',
 81: 'W_Nabellen incomplete dossiers',
 82: 'W_Nabellen incomplete dossiers',
 83: 'W_Nabellen incomplete dossiers',
 84: 'W_Nabellen incomplete dossiers',
 85: 'W_Nabellen incomplete dossiers',
 86: 'W_Nabellen incomplete dossiers',
 87: 'W_Nabellen incomplete dossiers',
 88: 'W_Nabellen incomplete dossiers',
 89: 'W_Nabellen incomplete dossiers',
 90: 'W_Nabellen incomplete dossiers',
 91: 'W_Nabellen incomplete dossiers',
 92: 'W_Nabellen incomplete dossiers',
 93: 'W_Nabellen incomplete dossiers',
 94: 'W_Nabellen incomplete dossiers',
 95: 'W_Nabellen incomplete dossiers',
 96: 'W_Nabellen incomplete dossiers',
 97: 'W_Nabellen incomplete dossiers',
 98: 'W_Nabellen incomplete dossiers',
 99: 'W_Nabellen incomplete dossiers',
 100: 'W_Nabellen incomplete dossiers',
 101: 'W_Nabellen incomplete dossiers',
 102: 'W_Nabellen incomplete dossiers',
 103: 'W_Nabellen incomplete dossiers',
 104: 'W_Nabellen incomplete dossiers',
 105: 'W_Nabellen incomplete dossiers',
 106: 'W_Nabellen incomplete dossiers',
 107: 'W_Nabellen incomplete dossiers',
 108: 'W_Nabellen incomplete dossiers',
 109: 'W_Nabellen incomplete dossiers',
 110: 'W_Nabellen incomplete dossiers',
 111: 'W_Nabellen incomplete dossiers',
 112: 'W_Nabellen incomplete dossiers',
 113: 'W_Nabellen incomplete dossiers',
 114: 'W_Nabellen incomplete dossiers',
 115: 'W_Nabellen incomplete dossiers',
 116: 'W_Nabellen incomplete dossiers',
 117: 'W_Nabellen incomplete dossiers',
 118: 'W_Nabellen incomplete dossiers',
 119: 'W_Nabellen incomplete dossiers',
 120: 'W_Nabellen incomplete dossiers',
 121: 'W_Nabellen incomplete dossiers',
 122: 'W_Nabellen incomplete dossiers',
 123: 'W_Nabellen incomplete dossiers',
 124: 'W_Nabellen incomplete dossiers',
 125: 'W_Nabellen incomplete dossiers',
 126: 'W_Nabellen incomplete dossiers',
 127: 'W_Nabellen incomplete dossiers',
 128: 'W_Nabellen incomplete dossiers',
 129: 'W_Nabellen incomplete dossiers',
 130: 'W_Nabellen incomplete dossiers',
 131: 'W_Nabellen incomplete dossiers',
 132: 'W_Nabellen incomplete dossiers',
 133: 'W_Nabellen incomplete dossiers',
 134: 'W_Nabellen incomplete dossiers',
 135: 'W_Nabellen incomplete dossiers',
 136: 'W_Nabellen incomplete dossiers',
 137: 'W_Nabellen incomplete dossiers',
 138: 'W_Nabellen incomplete dossiers',
 139: 'W_Nabellen incomplete dossiers',
 140: 'W_Nabellen incomplete dossiers',
 141: 'W_Nabellen incomplete dossiers',
 142: 'W_Nabellen incomplete dossiers',
 143: 'W_Nabellen incomplete dossiers',
 144: 'W_Nabellen incomplete dossiers',
 145: 'W_Nabellen incomplete dossiers',
 146: 'W_Nabellen incomplete dossiers',
 147: 'W_Nabellen incomplete dossiers',
 148: 'W_Nabellen incomplete dossiers',
 149: 'W_Nabellen incomplete dossiers',
 150: 'W_Nabellen incomplete dossiers',
 151: 'W_Nabellen incomplete dossiers',
 152: 'W_Nabellen incomplete dossiers',
 153: 'W_Nabellen incomplete dossiers',
 154: 'W_Nabellen incomplete dossiers',
 155: 'W_Nabellen incomplete dossiers',
 156: 'W_Nabellen incomplete dossiers',
 157: 'W_Nabellen incomplete dossiers',
 158: 'W_Nabellen incomplete dossiers',
 159: 'W_Nabellen incomplete dossiers',
 160: 'W_Nabellen incomplete dossiers',
 161: 'W_Nabellen incomplete dossiers',
 162: 'W_Nabellen incomplete dossiers',
 163: 'W_Nabellen incomplete dossiers',
 164: 'W_Nabellen incomplete dossiers',
 165: 'W_Nabellen incomplete dossiers',
 166: 'W_Nabellen incomplete dossiers',
 167: 'A_CANCELLED',
 168: 'O_CANCELLED',
 169: 'W_Nabellen incomplete dossiers',
 170: 'W_Nabellen incomplete dossiers',
 171: 'W_Nabellen incomplete dossiers',
 172: 'O_CANCELLED',
 173: 'A_CANCELLED',
 174: 'W_Nabellen incomplete dossiers',
 175: 0,
 176: 0,
 177: 0,
 178: 0,
 179: 0,
 180: 0,
 181: 0,
 182: 0,
 183: 0,
 184: 0,
 185: 0,
 186: 0,
 187: 0,
 188: 0,
 189: 0,
 190: 0,
 191: 0,
 192: 0,
 193: 0,
 194: 0,
 195: 0,
 196: 0,
 197: 0,
 198: 0,
 199: 0,
 200: 0,
 201: 0,
 202: 0,
 203: 0,
 204: 0,
 205: 0,
 206: 0,
 207: 0,
 208: 0,
 209: 0,
 210: 0,
 211: 0,
 212: 0,
 213: 0,
 214: 0,
 215: 0,
 216: 0,
 217: 0,
 218: 0,
 219: 0,
 220: 0,
 221: 0,
 222: 0,
 223: 0,
 224: 0,
 225: 0,
 226: 0,
 227: 0,
 228: 0,
 229: 0,
 230: 0,
 231: 0,
 232: 0,
 233: 0,
 234: 0,
 235: 0,
 236: 0,
 237: 0,
 238: 0,
 239: 0,
 240: 0,
 241: 0,
 242: 0,
 243: 0,
 244: 0,
 245: 0,
 246: 0,
 247: 0,
 248: 0,
 249: 0,
 250: 0,
 251: 0,
 252: 0,
 253: 0,
 254: 0,
 255: 0,
 256: 0,
 257: 0,
 258: 0,
 259: 0,
 260: 0,
 261: 0,
 262: 0,
 263: 0,
 264: 0,
 265: 0,
 266: 0,
 267: 0,
 268: 0,
 269: 0,
 270: 0,
 271: 0,
 272: 0,
 273: 0,
 274: 0,
 275: 0,
 276: 0,
 277: 0,
 278: 0,
 279: 0,
 280: 0,
 281: 0,
 282: 0,
 283: 0,
 284: 0,
 285: 0,
 286: 0,
 287: 0,
 288: 0,
 289: 0,
 290: 0,
 291: 0,
 292: 0,
 293: 0,
 294: 0,
 295: 0,
 296: 0,
 297: 0,
 298: 0,
 299: 0,
 300: 0,
 301: 0,
 302: 0,
 303: 0,
 304: 0,
 305: 0,
 306: 0,
 307: 0,
 308: 0,
 309: 0,
 310: 0,
 311: 0,
 312: 0,
 313: 0,
 314: 0,
 315: 0,
 316: 0,
 317: 0,
 318: 0,
 319: 0,
 320: 0,
 321: 0,
 322: 0,
 323: 0,
 324: 0,
 325: 0,
 326: 0,
 327: 0,
 328: 0,
 329: 0,
 330: 0,
 331: 0,
 332: 0,
 333: 0,
 334: 0,
 335: 0,
 336: 0,
 337: 0,
 338: 0,
 339: 0,
 340: 0,
 341: 0,
 342: 0,
 343: 0,
 344: 0,
 345: 0,
 346: 0,
 347: 0,
 348: 0,
 349: 0,
 350: 0,
 351: 0,
 352: 0,
 353: 0,
 354: 0,
 355: 0,
 356: 0,
 357: 0,
 358: 0,
 359: 0,
 360: 0,
 361: 0,
 362: 0,
 363: 0,
 364: 0,
 365: 0,
 366: 0,
 367: 0,
 368: 0,
 369: 0,
 370: 0,
 371: 0,
 372: 0,
 373: 0,
 374: 0,
 375: 0,
 376: 0,
 377: 0,
 378: 0,
 379: 0,
 380: 0,
 381: 0,
 382: 0,
 383: 0,
 384: 0,
 385: 0,
 386: 0,
 387: 0,
 388: 0,
 389: 0,
 390: 0,
 391: 0,
 392: 0,
 393: 0,
 394: 0,
 395: 0,
 396: 0,
 397: 0,
 398: 0,
 399: 0,
 400: 0,
 401: 0,
 402: 0,
 403: 0,
 404: 0,
 405: 0,
 406: 0,
 407: 0,
 408: 0,
 409: 0,
 410: 0,
 411: 0,
 412: 0,
 413: 0,
 414: 0,
 415: 0,
 416: 0,
 417: 0,
 418: 0,
 419: 0,
 420: 0,
 421: 0,
 422: 0,
 423: 0,
 424: 0,
 425: 0,
 426: 0,
 427: 0,
 428: 0,
 429: 0,
 430: 0,
 431: 0,
 432: 0,
 433: 0,
 434: 0,
 435: 0,
 436: 0,
 437: 0,
 438: 0,
 439: 0,
 440: 0,
 441: 0,
 442: 0,
 443: 0,
 444: 0,
 445: 0,
 446: 0,
 447: 0,
 448: 0,
 449: 0,
 450: 0,
 451: 0,
 452: 0,
 453: 0,
 454: 0,
 455: 0,
 456: 0,
 457: 0,
 458: 0,
 459: 0,
 460: 0,
 461: 0,
 462: 0,
 463: 0,
 464: 0,
 465: 0,
 466: 0,
 467: 0,
 468: 0,
 469: 0,
 470: 0,
 471: 0,
 472: 0,
 473: 0,
 474: 0,
 475: 0,
 476: 0,
 477: 0,
 478: 0,
 479: 0,
 480: 0,
 481: 0,
 482: 0,
 483: 0,
 484: 0,
 485: 0,
 486: 0,
 487: 0,
 488: 0,
 489: 0,
 490: 0,
 491: 0,
 492: 0,
 493: 0,
 494: 0,
 495: 0,
 496: 0,
 497: 0,
 498: 0,
 499: 0,
 500: 0,
 501: 0,
 502: 0,
 503: 0,
 504: 0,
 505: 0,
 506: 0,
 507: 0,
 508: 0,
 509: 0,
 510: 0,
 511: 0,
 512: 0,
 513: 0,
 514: 0,
 515: 0,
 516: 0,
 517: 0,
 518: 0,
 519: 0,
 520: 0,
 521: 0,
 522: 0,
 523: 0,
 524: 0,
 525: 0,
 526: 0,
 527: 0,
 528: 0,
 529: 0,
 530: 0,
 531: 0,
 532: 0,
 533: 0,
 534: 0,
 535: 0,
 536: 0,
 537: 0,
 538: 0,
 539: 0,
 540: 0,
 541: 0,
 542: 0,
 543: 0,
 544: 0,
 545: 0,
 546: 0,
 547: 0,
 548: 0,
 549: 0,
 550: 0,
 551: 0,
 552: 0,
 553: 0,
 554: 0,
 555: 0,
 556: 0,
 557: 0,
 558: 0,
 559: 0,
 560: 0,
 561: 0,
 562: 0,
 563: 0,
 564: 0,
 565: 0,
 566: 0,
 567: 0,
 568: 0,
 569: 0,
 570: 0,
 571: 0,
 572: 0,
 573: 0,
 574: 0,
 575: 0,
 576: 0,
 577: 0,
 578: 0,
 579: 0,
 580: 0,
 581: 0,
 582: 0,
 583: 0,
 584: 0,
 585: 0,
 586: 0,
 587: 0,
 588: 0,
 589: 0,
 590: 0,
 591: 0,
 592: 0,
 593: 0,
 594: 0,
 595: 0,
 596: 0,
 597: 0,
 598: 0,
 599: 0,
 600: 0,
 601: 0,
 602: 0,
 603: 0,
 604: 0,
 605: 0,
 606: 0,
 607: 0,
 608: 0,
 609: 0,
 610: 0,
 611: 0,
 612: 0,
 613: 0,
 614: 0,
 615: 0,
 616: 0,
 617: 0,
 618: 0,
 619: 0,
 620: 0,
 621: 0,
 622: 0,
 623: 0,
 624: 0,
 625: 0,
 626: 0,
 627: 0,
 628: 0,
 629: 0,
 630: 0,
 631: 0,
 632: 0,
 633: 0,
 634: 0,
 635: 0,
 636: 0,
 637: 0,
 638: 0,
 639: 0,
 640: 0,
 641: 0,
 642: 0,
 643: 0,
 644: 0,
 645: 0,
 646: 0,
 647: 0,
 648: 0,
 649: 0,
 650: 0,
 651: 0,
 652: 0,
 653: 0,
 654: 0,
 655: 0,
 656: 0,
 657: 0,
 658: 0,
 659: 0,
 660: 0,
 661: 0,
 662: 0,
 663: 0,
 664: 0,
 665: 0,
 666: 0,
 667: 0,
 668: 0,
 669: 0,
 670: 0,
 671: 0,
 672: 0,
 673: 0,
 674: 0,
 675: 0,
 676: 0,
 677: 0,
 678: 0,
 679: 0,
 680: 0,
 681: 0,
 682: 0,
 683: 0,
 684: 0,
 685: 0,
 686: 0,
 687: 0,
 688: 0,
 689: 0,
 690: 0,
 691: 0,
 692: 0,
 693: 0,
 694: 0,
 695: 0,
 696: 0,
 697: 0,
 698: 0,
 699: 0,
 700: 0,
 701: 0,
 702: 0,
 703: 0,
 704: 0,
 705: 0,
 706: 0,
 707: 0,
 708: 0,
 709: 0,
 710: 0,
 711: 0,
 712: 0,
 713: 0,
 714: 0,
 715: 0,
 716: 0,
 717: 0,
 718: 0,
 719: 0,
 720: 0,
 721: 0,
 722: 0,
 723: 0,
 724: 0,
 725: 0,
 726: 0,
 727: 0,
 728: 0,
 729: 0,
 730: 0,
 731: 0,
 732: 0,
 733: 0,
 734: 0,
 735: 0,
 736: 0,
 737: 0,
 738: 0,
 739: 0,
 740: 0,
 741: 0,
 742: 0,
 743: 0,
 744: 0,
 745: 0,
 746: 0,
 747: 0,
 748: 0,
 749: 0,
 750: 0,
 751: 0,
 752: 0,
 753: 0,
 754: 0,
 755: 0,
 756: 0,
 757: 0,
 758: 0,
 759: 0,
 760: 0,
 761: 0,
 762: 0,
 763: 0,
 764: 0,
 765: 0,
 766: 0,
 767: 0,
 768: 0,
 769: 0,
 770: 0,
 771: 0,
 772: 0,
 773: 0,
 774: 0,
 775: 0,
 776: 0,
 777: 0,
 778: 0,
 779: 0,
 780: 0,
 781: 0,
 782: 0,
 783: 0,
 784: 0,
 785: 0,
 786: 0,
 787: 0,
 788: 0,
 789: 0,
 790: 0,
 791: 0,
 792: 0,
 793: 0,
 794: 0,
 795: 0,
 796: 0,
 797: 0,
 798: 0,
 799: 0,
 800: 0,
 801: 0,
 802: 0,
 803: 0,
 804: 0,
 805: 0,
 806: 0,
 807: 0,
 808: 0,
 809: 0,
 810: 0,
 811: 0,
 812: 0,
 813: 0,
 814: 0,
 815: 0,
 816: 0,
 817: 0,
 818: 0,
 819: 0,
 820: 0,
 821: 0,
 822: 0,
 823: 0,
 824: 0,
 825: 0,
 826: 0,
 827: 0,
 828: 0,
 829: 0,
 830: 0,
 831: 0,
 832: 0,
 833: 0,
 834: 0,
 835: 0,
 836: 0,
 837: 0,
 838: 0,
 839: 0,
 840: 0,
 841: 0,
 842: 0,
 843: 0,
 844: 0,
 845: 0,
 846: 0,
 847: 0,
 848: 0,
 849: 0,
 850: 0,
 851: 0,
 852: 0,
 853: 0,
 854: 0,
 855: 0,
 856: 0,
 857: 0,
 858: 0,
 859: 0,
 860: 0,
 861: 0,
 862: 0,
 863: 0,
 864: 0,
 865: 0,
 866: 0,
 867: 0,
 868: 0,
 869: 0,
 870: 0,
 871: 0,
 872: 0,
 873: 0,
 874: 0,
 875: 0,
 876: 0,
 877: 0,
 878: 0,
 879: 0,
 880: 0,
 881: 0,
 882: 0,
 883: 0,
 884: 0,
 885: 0,
 886: 0,
 887: 0,
 888: 0,
 889: 0,
 890: 0,
 891: 0,
 892: 0,
 893: 0,
 894: 0,
 895: 0,
 896: 0,
 897: 0,
 898: 0,
 899: 0,
 900: 0,
 901: 0,
 902: 0,
 903: 0,
 904: 0,
 905: 0,
 906: 0,
 907: 0,
 908: 0,
 909: 0,
 910: 0,
 911: 0,
 912: 0,
 913: 0,
 914: 0,
 915: 0,
 916: 0,
 917: 0,
 918: 0,
 919: 0,
 920: 0,
 921: 0,
 922: 0,
 923: 0,
 924: 0,
 925: 0,
 926: 0,
 927: 0,
 928: 0,
 929: 0,
 930: 0,
 931: 0,
 932: 0,
 933: 0,
 934: 0,
 935: 0,
 936: 0,
 937: 0,
 938: 0,
 939: 0,
 940: 0,
 941: 0,
 942: 0,
 943: 0,
 944: 0,
 945: 0,
 946: 0,
 947: 0,
 948: 0,
 949: 0,
 950: 0,
 951: 0,
 952: 0,
 953: 0,
 954: 0,
 955: 0,
 956: 0,
 957: 0,
 958: 0,
 959: 0,
 960: 0,
 961: 0,
 962: 0,
 963: 0,
 964: 0,
 965: 0,
 966: 0,
 967: 0,
 968: 0,
 969: 0,
 970: 0,
 971: 0,
 972: 0,
 973: 0,
 974: 0,
 975: 0,
 976: 0,
 977: 0,
 978: 0,
 979: 0,
 980: 0,
 981: 0,
 982: 0,
 983: 0,
 984: 0,
 985: 0,
 986: 0,
 987: 0,
 988: 0,
 989: 0,
 990: 0,
 991: 0,
 992: 0,
 993: 0,
 994: 0,
 995: 0,
 996: 0,
 997: 0,
 998: 0,
 999: 0,
 ...}

In [41]:
# #create next time list
#     nexttime_lst1 = [time for time in df_case['time and date']]
#     nexttime_lst = nexttime_lst1[1:]
#     nexttime_lst.append(nexttime_lst[-1])
    
#     #create difference list
#     time_diff = []
#     for i in range(len(nexttime_lst)):
#         time_diff.append(nexttime_lst[i] - nexttime_lst1[i])

In [42]:
df_result = pd.DataFrame()

for case in cases: 
    
    df_case = df_train[df_train['case concept:name'] == case].copy().reset_index()

    pred_list = [position_dict[i] for i in range(len(df_case))]
    pred_list = pred_list[1:]
    pred_list.append('-')

    

    
    #create next event list
    event_lst = [event for event in df_case['event concept:name']]
    event_lst = event_lst[1:]
    event_lst.append('-')
    
    #create next time list
    nexttime_lst1 = [time for time in df_case['time and date']]
    nexttime_lst = nexttime_lst1[1:]
    nexttime_lst.append(nexttime_lst[-1])
    
    #create difference list
    time_diff = []
    for i in range(len(nexttime_lst)):
        time_diff.append(nexttime_lst[i] - nexttime_lst1[i])
    
    #append columns to df case
    df_case['Next event'] = event_lst
    df_case['Time to next event'] = time_diff


    df_case['Event prediction'] = pred_list
    
    #append df case to final df
    df_result = df_result.append(df_case)

In [43]:
df_result.head()

,index,eventID,case concept:name,case REG_DATE,case AMOUNT_REQ,event concept:name,event lifecycle:transition,event time:timestamp,time and date,Next event,Time to next event,Event prediction
0,0,0,173688,2011-10-01T00:38:44.546+02:00,20000,A_SUBMITTED,COMPLETE,01-10-2011 00:38:44.546,2011-10-01 00:38:44,A_PARTLYSUBMITTED,0 days 00:00:00,A_PARTLYSUBMITTED
1,1,1,173688,2011-10-01T00:38:44.546+02:00,20000,A_PARTLYSUBMITTED,COMPLETE,01-10-2011 00:38:44.880,2011-10-01 00:38:44,A_PREACCEPTED,0 days 00:00:53,W_Afhandelen leads
2,2,2,173688,2011-10-01T00:38:44.546+02:00,20000,A_PREACCEPTED,COMPLETE,01-10-2011 00:39:37.906,2011-10-01 00:39:37,W_Completeren aanvraag,0 days 00:00:01,W_Afhandelen leads
3,3,3,173688,2011-10-01T00:38:44.546+02:00,20000,W_Completeren aanvraag,SCHEDULE,01-10-2011 00:39:38.875,2011-10-01 00:39:38,W_Completeren aanvraag,0 days 10:57:08,W_Completeren aanvraag
4,89,4,173688,2011-10-01T00:38:44.546+02:00,20000,W_Completeren aanvraag,START,01-10-2011 11:36:46.437,2011-10-01 11:36:46,A_ACCEPTED,0 days 00:05:57,W_Completeren aanvraag

In [44]:
time_dict = {}
for case in cases:
    df_case = df_result[df_result['case concept:name'] == case].copy()
    df_case.reset_index(inplace=True)
    for index, row in df_case.iterrows():
        if index in time_dict:
            time_dict[index]['sum'] += row['Time to next event']
            time_dict[index]['count'] += 1
        else:
            time_dict[index] = {'sum': row['Time to next event'], 'count': 1}

In [45]:
mean_time_dict = {}
for position in time_dict.keys():
    mean_time = time_dict[position]['sum'] / time_dict[position]['count']
    mean_time_dict[position] = mean_time

In [46]:
mean_time_dict

{0: Timedelta('0 days 00:00:00.572165440'),
 1: Timedelta('0 days 00:00:35.112904766'),
 2: Timedelta('0 days 02:07:15.338618779'),
 3: Timedelta('0 days 03:15:52.908085872'),
 4: Timedelta('0 days 00:17:50.047049749'),
 5: Timedelta('0 days 02:55:00.800231392'),
 6: Timedelta('0 days 01:01:59.411264441'),
 7: Timedelta('0 days 03:53:58.768229601'),
 8: Timedelta('0 days 02:46:51.519950997'),
 9: Timedelta('0 days 03:43:09.446972411'),
 10: Timedelta('0 days 02:52:50.471021332'),
 11: Timedelta('0 days 23:53:22.470870986'),
 12: Timedelta('0 days 03:05:09.173168789'),
 13: Timedelta('1 days 10:43:11.757661290'),
 14: Timedelta('0 days 08:50:31.370807453'),
 15: Timedelta('1 days 08:19:56.959482038'),
 16: Timedelta('0 days 12:54:23.140772532'),
 17: Timedelta('1 days 03:08:32.116083009'),
 18: Timedelta('0 days 15:46:13.963903743'),
 19: Timedelta('1 days 00:15:10.413699864'),
 20: Timedelta('0 days 18:36:11.491803278'),
 21: Timedelta('0 days 19:50:37.431247036'),
 22: Timedelta('0 days 18:39:51.665510406'),
 23: Timedelta('0 days 18:49:06.145051624'),
 24: Timedelta('0 days 17:57:07.125333333'),
 25: Timedelta('0 days 18:57:45.464726873'),
 26: Timedelta('0 days 17:59:30.658892128'),
 27: Timedelta('0 days 17:10:32.658021712'),
 28: Timedelta('0 days 17:36:28.934726688'),
 29: Timedelta('0 days 15:09:17.794411177'),
 30: Timedelta('0 days 15:36:16.752908001'),
 31: Timedelta('0 days 14:31:32.717037037'),
 32: Timedelta('0 days 16:38:25.467532467'),
 33: Timedelta('0 days 14:50:34.718892104'),
 34: Timedelta('0 days 15:04:32.987280701'),
 35: Timedelta('0 days 11:39:21.126452812'),
 36: Timedelta('0 days 13:54:42.895434462'),
 37: Timedelta('0 days 12:10:41.167788710'),
 38: Timedelta('0 days 12:24:53.588202866'),
 39: Timedelta('0 days 10:14:54.339953271'),
 40: Timedelta('0 days 12:30:49.983920841'),
 41: Timedelta('0 days 10:07:37.801169590'),
 42: Timedelta('0 days 11:08:53.283136710'),
 43: Timedelta('0 days 08:45:44.672275054'),
 44: Timedelta('0 days 11:14:13.334883720'),
 45: Timedelta('0 days 09:30:25.801313628'),
 46: Timedelta('0 days 10:12:11.511811023'),
 47: Timedelta('0 days 09:15:48.605166051'),
 48: Timedelta('0 days 09:32:32.843657817'),
 49: Timedelta('0 days 07:44:37.615706806'),
 50: Timedelta('0 days 09:02:52.741457858'),
 51: Timedelta('0 days 07:49:23.133574007'),
 52: Timedelta('0 days 09:33:30.088010204'),
 53: Timedelta('0 days 08:07:06.283044058'),
 54: Timedelta('0 days 09:37:35.550143266'),
 55: Timedelta('0 days 08:26:14.937784522'),
 56: Timedelta('0 days 09:40:15.841680129'),
 57: Timedelta('0 days 12:28:53.175043327'),
 58: Timedelta('0 days 10:06:09.062271062'),
 59: Timedelta('0 days 08:19:01.373076923'),
 60: Timedelta('0 days 10:27:07.448132780'),
 61: Timedelta('0 days 07:07:08.327433628'),
 62: Timedelta('0 days 09:33:11.320843091'),
 63: Timedelta('0 days 07:07:44.178921568'),
 64: Timedelta('0 days 09:01:43.773684210'),
 65: Timedelta('0 days 07:17:01.737127371'),
 66: Timedelta('0 days 11:11:04.530259365'),
 67: Timedelta('0 days 04:33:14.979041916'),
 68: Timedelta('0 days 10:29:36.663492063'),
 69: Timedelta('0 days 07:40:44.932203389'),
 70: Timedelta('0 days 09:13:09.840740740'),
 71: Timedelta('0 days 05:28:59.286274509'),
 72: Timedelta('0 days 07:08:20.975000'),
 73: Timedelta('0 days 06:13:35.052401746'),
 74: Timedelta('0 days 07:06:59.990566037'),
 75: Timedelta('0 days 04:10:03.885000'),
 76: Timedelta('0 days 09:54:35.952631578'),
 77: Timedelta('0 days 05:17:43.314606741'),
 78: Timedelta('0 days 06:06:57.832335329'),
 79: Timedelta('0 days 04:15:51.093750'),
 80: Timedelta('0 days 15:32:21.486666666'),
 81: Timedelta('0 days 07:34:49.979020979'),
 82: Timedelta('0 days 08:22:32.886363636'),
 83: Timedelta('0 days 11:31:40.492187500'),
 84: Timedelta('0 days 13:29:19'),
 85: Timedelta('0 days 07:23:37.573913043'),
 86: Timedelta('0 days 10:51:54.066037735'),
 87: Timedelta('0 days 09:22:35.186274509'),
 88: Timedelta('0 days 09:37:07.690721649'),
 89: Timedelta('0 days 05:52:28.389473684'),
 90: Timedelta('0 days 06:45:31.325842696'),
 91: Timedelta('0 days 08:06:20.870588235'),
 92: Timedelta('0 days 11:22:13.234567901'),
 93: Timedelta('0 days 14:07:16.705128205'),
 94: Timedelta('0 days 10:49:21.706666666'),
 95: Timedelta('0 days 06:34:31.194444444'),
 96: Timedelta('0 days 07:10:52.971014492'),
 97: Timedelta('0 days 03:51:35.384615384'),
 98: Timedelta('0 days 08:13:25.968253968'),
 99: Timedelta('0 days 09:01:39.716666666'),
 100: Timedelta('0 days 07:59:17.526315789'),
 101: Timedelta('0 days 09:02:58.200000'),
 102: Timedelta('0 days 05:53:00.169811320'),
 103: Timedelta('0 days 06:08:12.230769230'),
 104: Timedelta('0 days 09:14:54.812500'),
 105: Timedelta('0 days 04:56:06.958333333'),
 106: Timedelta('0 days 05:20:41.872340425'),
 107: Timedelta('0 days 03:38:30.133333333'),
 108: Timedelta('0 days 05:36:42.162790697'),
 109: Timedelta('0 days 02:45:47.825000'),
 110: Timedelta('0 days 06:48:45.282051282'),
 111: Timedelta('0 days 06:55:02.305555555'),
 112: Timedelta('0 days 08:29:36.911764705'),
 113: Timedelta('0 days 07:33:22.937500'),
 114: Timedelta('0 days 11:12:18.562500'),
 115: Timedelta('0 days 05:55:29.100000'),
 116: Timedelta('0 days 10:59:01.142857142'),
 117: Timedelta('0 days 03:51:52.285714285'),
 118: Timedelta('0 days 12:30:03.600000'),
 119: Timedelta('0 days 03:21:32.739130434'),
 120: Timedelta('0 days 11:43:53.913043478'),
 121: Timedelta('0 days 14:40:55.391304347'),
 122: Timedelta('0 days 06:06:43.090909090'),
 123: Timedelta('1 days 01:14:16.727272727'),
 124: Timedelta('0 days 09:53:38.047619047'),
 125: Timedelta('0 days 13:41:58.210526315'),
 126: Timedelta('0 days 20:06:04.555555555'),
 127: Timedelta('0 days 14:19:26.250000'),
 128: Timedelta('0 days 20:22:43.533333333'),
 129: Timedelta('0 days 05:12:49.666666666'),
 130: Timedelta('0 days 12:16:02.538461538'),
 131: Timedelta('0 days 02:24:18.416666666'),
 132: Timedelta('0 days 07:05:10.416666666'),
 133: Timedelta('0 days 03:13:21.100000'),
 134: Timedelta('0 days 00:09:28.300000'),
 135: Timedelta('0 days 18:03:37.900000'),
 136: Timedelta('0 days 07:55:23'),
 137: Timedelta('0 days 13:12:32.777777777'),
 138: Timedelta('0 days 00:22:49.333333333'),
 139: Timedelta('1 days 01:59:09.777777777'),
 140: Timedelta('0 days 02:07:40.555555555'),
 141: Timedelta('0 days 02:34:59.250000'),
 142: Timedelta('0 days 03:05:28.571428571'),
 143: Timedelta('0 days 12:11:54.428571428'),
 144: Timedelta('0 days 01:38:58'),
 145: Timedelta('0 days 13:36:27.714285714'),
 146: Timedelta('0 days 10:17:02.857142857'),
 147: Timedelta('0 days 06:54:59.857142857'),
 148: Timedelta('0 days 10:27:30.714285714'),
 149: Timedelta('1 days 14:00:09.571428571'),
 150: Timedelta('0 days 14:33:20'),
 151: Timedelta('0 days 00:10:12.833333333'),
 152: Timedelta('0 days 22:42:59.500000'),
 153: Timedelta('0 days 00:06:17.166666666'),
 154: Timedelta('0 days 02:47:10.166666666'),
 155: Timedelta('0 days 01:47:59.833333333'),
 156: Timedelta('0 days 02:54:58.166666666'),
 157: Timedelta('0 days 00:52:14.333333333'),
 158: Timedelta('0 days 00:43:01.166666666'),
 159: Timedelta('0 days 00:03:28.200000'),
 160: Timedelta('0 days 01:11:09.200000'),
 161: Timedelta('0 days 04:33:03.750000'),
 162: Timedelta('0 days 09:31:13.500000'),
 163: Timedelta('0 days 06:48:06.333333333'),
 164: Timedelta('0 days 00:08:04.666666666'),
 165: Timedelta('0 days 02:15:19.333333333'),
 166: Timedelta('2 days 04:47:03.666666666'),
 167: Timedelta('0 days 00:01:22'),
 168: Timedelta('0 days 00:22:08'),
 169: Timedelta('0 days 00:00:07.500000'),
 170: Timedelta('0 days 00:26:09'),
 171: Timedelta('0 days 00:05:05'),
 172: Timedelta('0 days 00:00:00'),
 173: Timedelta('0 days 00:00:04'),
 174: Timedelta('0 days 00:00:00')}

In [47]:
lst = []
for case in cases:
    df_case = df_result[df_result['case concept:name'] == case].copy()
    df_case.reset_index(inplace=True)
    for index, row in df_case.iterrows():
        time = mean_time_dict[index]
        lst.append(time)

In [48]:
df_result['Time prediction'] = lst

In [49]:
int_dict = {}
for case in cases:
    df_case = df_train[df_train['case concept:name'] == case].reset_index()
    for index, row in df_case.iterrows():
        if row['event concept:name'] in int_dict:
            if index in int_dict[row['event concept:name']]:
                int_dict[row['event concept:name']][index] += 1
            else:
                int_dict[row['event concept:name']].update({index: 1})
        else:
            int_dict[row['event concept:name']] = {index: 1}

In [50]:
df_result.head()

,index,eventID,case concept:name,case REG_DATE,case AMOUNT_REQ,event concept:name,event lifecycle:transition,event time:timestamp,time and date,Next event,Time to next event,Event prediction,Time prediction
0,0,0,173688,2011-10-01T00:38:44.546+02:00,20000,A_SUBMITTED,COMPLETE,01-10-2011 00:38:44.546,2011-10-01 00:38:44,A_PARTLYSUBMITTED,0 days 00:00:00,A_PARTLYSUBMITTED,0 days 00:00:00.572165440
1,1,1,173688,2011-10-01T00:38:44.546+02:00,20000,A_PARTLYSUBMITTED,COMPLETE,01-10-2011 00:38:44.880,2011-10-01 00:38:44,A_PREACCEPTED,0 days 00:00:53,W_Afhandelen leads,0 days 00:00:35.112904766
2,2,2,173688,2011-10-01T00:38:44.546+02:00,20000,A_PREACCEPTED,COMPLETE,01-10-2011 00:39:37.906,2011-10-01 00:39:37,W_Completeren aanvraag,0 days 00:00:01,W_Afhandelen leads,0 days 02:07:15.338618779
3,3,3,173688,2011-10-01T00:38:44.546+02:00,20000,W_Completeren aanvraag,SCHEDULE,01-10-2011 00:39:38.875,2011-10-01 00:39:38,W_Completeren aanvraag,0 days 10:57:08,W_Completeren aanvraag,0 days 03:15:52.908085872
4,89,4,173688,2011-10-01T00:38:44.546+02:00,20000,W_Completeren aanvraag,START,01-10-2011 11:36:46.437,2011-10-01 11:36:46,A_ACCEPTED,0 days 00:05:57,W_Completeren aanvraag,0 days 00:17:50.047049749

# Accuracy

In [51]:
correct_event = 0 
correct_time = 0
total = 0
for index, row in df_result.iterrows():
    total += 1
    if row['Next event'] == row['Event prediction']:
        correct_event += 1
    if row['Time to next event'] == row['Time prediction']:
        correct_time += 1
        
accuracy_event = correct_event/total 
accuracy_time = correct_time/total

accuracy_event, accuracy_time

(0.48038269030726244, 2.332339756597023e-05)